### ISSUE TITLE
Cluster size and unfocused cluster number

### ISSUE THREAD

**Issue by newera912** [phanein/focused-clustering#1]
HI,
I am working on some experiment on FocusCO method. 
Current experiment results I found out FocusCO is working very well on the datasets with small number of cluster with big cluster size. In my experiment we generate cluster size with {30,40,....100,150,200} and number of cluster {3,4,...15}. We only choose **one cluster as the focused cluster** , the 20 feature and and set the randomly chose 10 features as the focused cluster. all the other setting is used the default one.
Fondings: 
(small_cluster_size,big_cluster_number) :   the result is not good. F-score=0. 35 for focused cluster. 
(small_cluster_size,small_cluster_number): the result is good.     F-score=0. 7 for focused cluster. 
(big_cluster_size,small_cluster_number) :   the results is good.    F-score=1.0 for focused cluster. 
(big_cluster_size,big_cluster_number) :      the results is good.    F-score=1.0 for focused cluster. 

Is this correct observation or I need to change some parameter settings(gamma or the DissimilarSamples )?
It is very nice of you if you reply in short time. 
Thank you very much..

**Comment by newera912** [comment]
Hi,
Another problem is,in your paper "Focused Clustering and Outlier Detection
in Large Attributed Graphs" , section 4.1.1 when you generating the simulation data, the variance is 0.001 or the standard deviation is 0.001? just for confirm. We setting the \sigma^2=0.001 ,\sigma=0.0316.

**Comment by phanein** [comment]
These are some detailed questions (and its been a while), so take my answers with a grain of salt.

1.  In general, as the number of clusters increases, recall will go down.  However, that seems a bit low.  Maybe your ratio of positive / negative examples is off (or the you need to play with gamma).  Are you taking enough positive samples when the focused cluster is small?  Are the focus vectors you're learning sparse (ideally they should be) ?

2. Good catch on the standard deviation.  That's a typo (had to go back to original code).  I believe this is the relevant line, and so standard deviation is 0.001.

                if (chosen_features(i,k))
                    X(j,k) = random('normal', chosen_means(i,k), 0.001, 1, 1);
                end

**Comment by newera912** [comment]
Thank you for your reply. 
yes, I tried different number of positive example number. Can you give some suggestion for range of gamma and  the dissimilarity ratio. Default is gamma=1.0 and dissimilarity_ratio is = 2.0*size_of_user_input_example. 
Yes, The learned focus vector is sparse.
